x-spark-common:
  &spark-common
  networks:
    - spark_network
  volumes:
    - ./src:/src

services:
  spark:
    <<: *spark-common
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-container
    ports:
      - "4040:4040"
      - "7077:7077"
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=4040
      - BITNAMI_DEBUG=true

  spark-worker1:
    <<: *spark-common
    image: bitnami/spark:latest
    container_name: spark-worker1
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-container:7077
      - SPARK_WORKER_MEMORY=2G

  spark-worker2:
    <<: *spark-common
    image: bitnami/spark:latest
    container_name: spark-worker2
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-container:7077
      - SPARK_WORKER_MEMORY=2G

  spark_notebook:
    <<: *spark-common
    build:
      context: .
      dockerfile: Dockerfilejupyter
    container_name: spark-notebook
    depends_on:
      - spark
    ports:
      - "8888:8888"

      
volumes:
  hive-postgres-db-volume:

networks:
  spark_network:
    name: spark_network
    driver: bridge