services:
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spark-container
    networks:
      - spark_network
    ports:
      - "4040:4040"
      - "7077:7077"
    volumes:
      - ./src:/opt/bitnami/spark/src
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=4040
      - BITNAMI_DEBUG=true

  spark-worker1:
    image: bitnami/spark:latest
    container_name: spark-worker1
    networks:
      - spark_network
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-container:7077
      - SPARK_WORKER_MEMORY=2G

  spark-worker2:
    image: bitnami/spark:latest
    container_name: spark-worker2
    networks:
      - spark_network
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-container:7077
      - SPARK_WORKER_MEMORY=2G

  spark_notebook:
    build:
      context: .
      dockerfile: Dockerfilejupyter
    container_name: spark-notebook
    networks:
      - spark_network
    depends_on:
      - spark
    ports:
      - "8888:8888"

networks:
  spark_network:
    name: spark_network
    driver: bridge 