x-spark-common:
  &spark-common
  volumes:
    - ./spark_apps:/opt/spark/apps
    - spark-logs:/opt/spark/spark-events
  networks:
      - airflow_default

services:
  spark-master:
    <<: *spark-common
    container_name: da-spark-master
    build: .
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'


  spark-history-server:
    <<: *spark-common
    container_name: da-spark-history
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    ports:
      - '18080:18080'

  spark-worker:
    <<: *spark-common
    image: da-spark-image
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    environment:
      - SPARK_WORKER_MEMORY=2G

volumes:
  spark-logs:


networks:
  airflow_default:
    external: true
  