services:
  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio:/data
    env_file:
      - .env
    networks:
      - spark_network

volumes:
  minio:


networks:
  spark_network:
    external: true
    driver: bridge